name: Shaun's Blog
description: A reverie from the monotony of a reality where food is still at least as important as thoughts
author: Shaun M. Roberts
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"